version: '3.8'

services:
  training:
    #Build the container using Dockerfile.train
    build:
      context: .
      dockerfile: Dockerfile.train
    # Use a shared volume to store the trained model
    volumes:
      - model_storage:/app/models
    # TODO: Set the command to run the training script
    command:
    restart: on-failure

  inference:
    # TODO: Build the container using Dockerfile.infer
    build:
      context: 
      dockerfile: 
    #Use a shared volume to load the trained model
    volumes:
      - model_storage:/app/models
    # TODO: Expose port 8080 (or any other port) for the Flask app
    ports:
      - 
    #Ensure that the inference service starts after the training service is complete
    depends_on:
      - training
    command: ["python", "server.py"]

#Define a shared volume for the model file
volumes:
  model_storage:
    driver: local
